name: CI
on:
  push:
    branches: [main, feat/yandexgpt-flow]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Prisma generate
        run: npx prisma generate
        env:
          DATABASE_URL: 'file:./ci.db'

      - run: npm run build

      # ❗ Офлайновый smoke: проверяем, что сборка существует,
      # но НИКАКИХ запросов к OpenAI/Яндексу не делаем.
      - name: Smoke (offline, no network)
        run: |
          test -f dist/core/llm.js
          node -e "require('fs').accessSync('dist/core/llm.js'); console.log('smoke-ok')"
        env:
          NODE_ENV: test
          # Дефолтные заглушки — чтобы ни один валидатор не ругался
          LLM_PROVIDER: yandex
          YANDEX_API_KEY: dummy
          YANDEX_FOLDER_ID: b1test
          YANDEX_MODEL: gpt://b1test/yandexgpt-lite/latest
          OPENAI_API_KEY: sk-FAKE
          BOT_TOKEN: '0000000000:FAKE'
          ADMIN_IDS: '726959884'
          METRICS_ENABLED: 'false'
          REPORT_V2: 'false'
          DATABASE_URL: 'file:./ci.db'
